

services:
  app:
    container_name: config-server
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "8888:8888"                  
    environment:
      CONFIG_SERVER_DB_URL: jdbc:postgresql://db:5432/cloud_config_sever?currentSchema=config_schema
      PET_DB_USER: root
      PET_DB_PSWD: root
    depends_on:
      - db

  db:
    container_name: config-db
    image: postgres:latest            # Use the latest PostgreSQL image
    restart: always
    environment:
      POSTGRES_DB: cloud_config_sever          # Name of the database to create
      POSTGRES_USER: root       # Database user
      POSTGRES_PASSWORD: root   # Database password
    ports:
      - "5432:5432"                    # Map host port 5432 to container port 5432