CREATE TABLE properties (
  id SERIAL PRIMARY KEY,
  APPLICATION VARCHAR(100) NOT NULL,
  PROFILE VARCHAR(10000)  NOT NULL,
  LABEL VARCHAR(100)  NOT NULL,
  PROP_KEY VARCHAR(100)  NOT NULL,
  VALUE VARCHAR(100)  NOT NULL,
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO properties(APPLICATION, PROFILE, LABEL, PROP_KEY, VALUE)
VALUES
('pet-consumer', 'dev', 'latest', 'pet.api.base.url', 'http://localhost:8785/api/v1/pets')